project:
  type: website
  output-dir: docs

website:
  title: "Emily's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar:
    top:
      - href: projects/scorecard_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

