---
title: "Where we're from."
editor: visual
---

```{r}
#install.packages(googlesheets4)
library(tidyverse)
library(maps)
library(googlesheets4)


class_info <- read_sheet("https://docs.google.com/spreadsheets/d/1XOAFQvBcFvhKwEl5xH6l3nRJK2Wk0hWZ18S9kAZclQ0/edit?usp=sharing") |>
  janitor::clean_names()

# selecting only the column we are interested in and making it into a vector.
country_vector <- as.vector( 
  class_info |>
    select("country"))
```

```{r}
class_maps <- function(country_vector){
  
  # Put the body of your function here, don't overthink it.
  map(regions = country_vector$country)
  
}
# If the line below throws an error its possible your country is not in the database or mispelled. 
class_maps(country_vector)
```

```{r}
# A function for finding appropriate names of countries

# A test vector
sub_vector<- country_vector$country

map_names <- function(name){
  # The first line makes sure we have a string
  name <- as.character(name)
  
  # All 1600 names are in the database can be save as follows
  vector_of_names <- map(plot = FALSE)$names
  
  # This gets a vector of boolean values. 
  Truths <- name %in% vector_of_names
  
  
  print("The following countries are in the databse")
  
  # This goes back to our original vector and extrance only the true names. 
  print(name[Truths])
  
  print("The following countries are not in the databse")
  
  # This goes back to our original vector and extrance only the true names. 
  print(name[Truths == FALSE])
  
}
map_names(sub_vector)


```
